---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle23cfree 
  namespace: oracle-namespace
  labels:
    app: database
    version: 23.2.0.1
spec:
  serviceName: "oracle23cfree"
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 23.2.0.1
  template:
    metadata:
      name: oracle23cfree
      labels:
        app: database
        version: 23.2.0.1
    spec:
      securityContext:
        fsGroup: 54321
      volumes:
         - name: dshm
           emptyDir:
             medium: Memory
             sizeLimit: 10Gi
      imagePullSecrets:
        - name: regcred 
      containers:
        - name: oracle23cfree
          image: container-registry.oracle.com/database/free:latest
          command:
          - /opt/oracle/runOracle.sh
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 2Gi
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: ora-data232
              mountPath: "/opt/oracle/oradata"
            - name: ora-setup232
              mountPath: "/opt/oracle/scripts/setup"
            - name: ora-startup232
              mountPath: "/opt/oracle/scripts/startup"
          env:
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PWD #Read the key call ORACLE_PWD
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_CHARACTERSET #Read the key call ORACLE_CHARACTERSET
  volumeClaimTemplates:
  - metadata:
      name: ora-startup232 
    spec:
      storageClassName: px-csi-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-setup232
    spec:
      storageClassName: px-csi-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-data232
    spec:
      storageClassName: px-csi-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 12Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oracle23c
  namespace: oracle-namespace
  labels:
    app: database
    version: 23.2.0.1
spec:
  selector:
    app: database
    version: 23.2.0.1
  type: NodePort
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oemexpress
    protocol: TCP
    port: 5500
    targetPort: 5500
